---
:url: http://farm6.static.flickr.com/5162/5234031659_857acc4b63.jpg
:real_name: Eustaquio Santimano
:title: Night View from the Singapore Flyer
:url_photopage: http://www.flickr.com/photos/eustaquio/5234031659/
:username: Eustaquio Santimano
:taken_at: 2010-11-18 20:19:53.000000000 +00:00
:license_name: Attribution-NonCommercial-NoDerivs License
:license_url: http://creativecommons.org/licenses/by-nc-nd/2.0/
