---
:url: http://farm6.static.flickr.com/5023/5578283926_8911bbd314.jpg
:real_name: paul (dex) bica
:title: predawn
:url_photopage: http://www.flickr.com/photos/dexxus/5578283926/
:username: paul bica
:taken_at: 2011-01-31 11:15:05.000000000 +00:00
:license_name: Attribution License
:license_url: http://creativecommons.org/licenses/by/2.0/
