---
:url: http://farm6.static.flickr.com/5215/5454729294_23e50dbee6.jpg
:real_name: Denis Collette
:title: Le vieux canoë rouge...!!! (7/9)
:url_photopage: http://www.flickr.com/photos/deniscollette/5454729294/
:username: Denis Collette...!!!
:taken_at: 2010-10-03 07:55:40.000000000 +00:00
:license_name: Attribution-NonCommercial-NoDerivs License
:license_url: http://creativecommons.org/licenses/by-nc-nd/2.0/
