---
:url: http://farm2.static.flickr.com/1330/5164203648_66d8856c0d.jpg
:real_name: Mike Behnken
:title: Living off the Land
:url_photopage: http://www.flickr.com/photos/mikebehnken/5164203648/
:username: MikeBehnken
:taken_at: 2010-10-30 12:34:22.000000000 -04:00
:license_name: Attribution-NoDerivs License
:license_url: http://creativecommons.org/licenses/by-nd/2.0/
