---
:url: http://farm6.static.flickr.com/5130/5330094813_1894d313f7.jpg
:real_name: Shandi-lee Cox
:title: I come alive in the night time
:url_photopage: http://www.flickr.com/photos/shandilee/5330094813/
:username: Shandi-lee
:taken_at: 2011-01-06 00:03:27.000000000 +00:00
:license_name: Attribution-NonCommercial-NoDerivs License
:license_url: http://creativecommons.org/licenses/by-nc-nd/2.0/
