---
:url: http://farm5.static.flickr.com/4149/5204343926_1cecf639ba.jpg
:real_name: H Matthew Howarth
:title: View Of Rum From Beinn Na Cille, Kingairloch
:url_photopage: http://www.flickr.com/photos/flatworldsedge/5204343926/
:username: flatworldsedge
:taken_at: 2010-11-24 14:30:27.000000000 +00:00
:license_name: Attribution-ShareAlike License
:license_url: http://creativecommons.org/licenses/by-sa/2.0/
