---
:url: http://farm6.static.flickr.com/5045/5270600203_d153f03ccb.jpg
:real_name: Kevin Dooley
:title: Dickens Village 2010
:url_photopage: http://www.flickr.com/photos/pagedooley/5270600203/
:username: kevin dooley
:taken_at: 2010-12-11 07:52:36.000000000 +00:00
:license_name: Attribution License
:license_url: http://creativecommons.org/licenses/by/2.0/
