---
:url: http://farm6.static.flickr.com/5133/5489333309_9fd7e0a7e9.jpg
:real_name: Shandi-lee Cox
:title: spring booties
:url_photopage: http://www.flickr.com/photos/shandilee/5489333309/
:username: Shandi-lee
:taken_at: 2011-03-01 14:25:03.000000000 +10:00
:license_name: Attribution-NonCommercial-NoDerivs License
:license_url: http://creativecommons.org/licenses/by-nc-nd/2.0/
