---
:url: http://farm6.static.flickr.com/5257/5529738150_6f295740bb.jpg
:real_name: David Yu
:title: San Francisco Golden Gate Bridge
:url_photopage: http://www.flickr.com/photos/davidyuweb/5529738150/
:username: davidyuweb
:taken_at: 2011-03-15 09:29:20.000000000 +00:00
:license_name: Attribution-NonCommercial-NoDerivs License
:license_url: http://creativecommons.org/licenses/by-nc-nd/2.0/
