---
:url: http://farm6.static.flickr.com/5010/5371659662_24f076cb2f.jpg
:real_name: Barry Yanowitz
:title: coney island bird man
:url_photopage: http://www.flickr.com/photos/tomvu/5371659662/
:username: Barry Yanowitz
:taken_at: 2010-12-25 12:00:00.000000000 -05:00
:license_name: Attribution-NonCommercial License
:license_url: http://creativecommons.org/licenses/by-nc/2.0/
