---
:url: http://farm2.static.flickr.com/1119/5152149731_260a73c6e7.jpg
:real_name: Brandon Warren
:title: Spirit of the Earth
:url_photopage: http://www.flickr.com/photos/brandoncwarren/5152149731/
:username: Brandon Christopher Warren
:taken_at: 2010-11-06 14:05:43.000000000 +10:00
:license_name: Attribution-NonCommercial License
:license_url: http://creativecommons.org/licenses/by-nc/2.0/
