---
:real_name: David Yu
:title: San Francisco Golden Gate Bridge
:url_photopage: http://www.flickr.com/photos/davidyuweb/5529738150/
:username: davidyuweb
:taken_at: 2011-03-15 09:29:20.000000000 +10:00
