---
:url: http://farm6.static.flickr.com/5121/5244978423_a0b15da57a.jpg
:real_name: ''
:title: Loneliness
:url_photopage: http://www.flickr.com/photos/balt-arts/5244978423/
:username: balt-arts
:taken_at: 2010-12-09 00:01:43.000000000 +00:00
:license_name: Attribution-NoDerivs License
:license_url: http://creativecommons.org/licenses/by-nd/2.0/
