---
:url: http://farm6.static.flickr.com/5135/5516993121_10f879e777.jpg
:real_name: ''
:title: Karl Oskar Lööw, Fredhäll, Uppland, Sweden
:url_photopage: http://www.flickr.com/photos/swedish_heritage_board/5516993121/
:username: Swedish National Heritage Board
:taken_at: 1933-01-01 00:00:00.000000000 +00:00
:license_name: No known copyright restrictions
:license_url: http://www.flickr.com/commons/usage/
