---
:url: http://farm5.static.flickr.com/4129/5192375946_6f96b23362.jpg
:real_name: David Yu
:title: San Francisco lucky double rainbow
:url_photopage: http://www.flickr.com/photos/davidyuweb/5192375946/
:username: davidyuweb
:taken_at: 2010-11-20 07:46:37.000000000 +00:00
:license_name: Attribution-NonCommercial-NoDerivs License
:license_url: http://creativecommons.org/licenses/by-nc-nd/2.0/
