---
:url: http://farm6.static.flickr.com/5047/5319373424_995f96e51c.jpg
:real_name: عبدالمجيد المطيويع
:title: Jeddah 2011
:url_photopage: http://www.flickr.com/photos/joodi/5319373424/
:username: Abdulmajeed Al.mutawee || twitter.com/almutawee
:taken_at: 2010-12-30 05:01:21.000000000 +00:00
:license_name: Attribution-NonCommercial-ShareAlike License
:license_url: http://creativecommons.org/licenses/by-nc-sa/2.0/
