---
:url: http://farm5.static.flickr.com/4110/5181018746_c40debd01a.jpg
:real_name: Sean Molin
:title: My, what fast glass you have. *Explored*
:url_photopage: http://www.flickr.com/photos/seanmolin/5181018746/
:username: Sean Molin Photography
:taken_at: 2010-11-16 00:13:27.000000000 +00:00
:license_name: Attribution-NonCommercial-NoDerivs License
:license_url: http://creativecommons.org/licenses/by-nc-nd/2.0/
