---
:url: http://farm6.static.flickr.com/5093/5438150166_8499fb90c3.jpg
:real_name: David Yu
:title: Palace of Fine Art twilight water reflection long exposure study
:url_photopage: http://www.flickr.com/photos/davidyuweb/5438150166/
:username: davidyuweb
:taken_at: 2011-02-11 22:40:53.000000000 -05:00
:license_name: Attribution-NonCommercial-NoDerivs License
:license_url: http://creativecommons.org/licenses/by-nc-nd/2.0/
